export enum MainActionsEnum {
    RESET_STATE = 'RESET_STATE',
    VALIDATE_OPERATION = 'VALIDATE_OPERATION',
    VALIDATE_PROVIDER = 'VALIDATE_PROVIDER',
    CALCULATE_TODAY_EXCHANGE_RATE = 'CALCULATE_TODAY_EXCHANGE_RATE',
    CALCULATE_EXCHANGE_RATE_VARIATION = 'CALCULATE_EXCHANGE_RATE_VARIATION',
    ASSIGN_INPUT_FOR_CALCULATE_EXCHANGE = 'ASSIGN_INPUT_FOR_CALCULATE_EXCHANGE',
    CALCULATE_EXCHANGE_BY_INPUT = 'CALCULATE_EXCHANGE_BY_INPUT',
}